version: '3.8'  #specifies docker compose version
services:
  web:
    build:
      context: ./      
    volumes:
      - .:/src
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*